### PR TITLE
Patch for iseg

### PR DESCRIPTION
**Pull request by darrylmasson**
The iseg somehow got partially forgotten during the 4.0 update campaign. This fixes that.

### CODE REVIEW

**Comment by darrylmasson** [comment]
Changes made as requested

**Comment by ramirezdiego** [comment]
In the mood to implement the ramping up/down confirmation request?

**Comment by darrylmasson** [comment]
The iseg doesn't have a ramp-down feature, and command confirmation is a non-trivial subsystem beyond the scope of this PR. I recommend opening an issue so it gets added to the list of desired features in the future.

**Comment by ramirezdiego** [comment]
Agree with opening an issue for the command confirmation.
On the other side, the iseg does have a ramp-down feature, so I guess you're referring to the code here.

**Pull request merged**
