### PR TITLE
Allow general pipeline configuation

### PR DESCRIPTION
**Pull request by adambrown1**
As well as putting configuration options per node under `node_config.node` you can put them under `pipeline_config` to be shared across the pipeline. Solves #164

### CODE REVIEW

**Review by darrylmasson — COMMENTED** [review]
What provisions are made to protect against cases where nodes take the same named value but do different things with them?

**Comment by adambrown1** [comment]
pipeline_config values are overwritten by node_config values. I would actually be happy with only having pipeline_config and no node_config, which would avoid any ambiguity. But assuming that someone creates two nodes which take the same named value and expect to do a different thing with it presumably they put one in the node_config and one in the pipeline_config (is there even another way to do it?) and then it will work like they expect

**Comment by darrylmasson** [comment]
I'm not opposed to adding this feature, but I will insist on it being done in a way that protects against the use of "reserved" config values, such as `length`. Also I think it would be better to have a `general` field (or equivalent) inside `node_config` rather than a new field at the highest level.

**Comment by adambrown1** [comment]
- Moved to node_config -> general
- I'm still not sure I understand the issue with "reserved" config values (which in this case just means ones that are used by default, depending on node class, rather than set by default right?). If I decide I want to specify BufferNode length for several buffer nodes in the pipeline I create, where is the problem with that? And if I want to specify it on a per-node level for the BufferNodes and have another length for other nodes, it will still work as expected. We could certainly ignore `length` entries from the `general` dictionary, but is it really worth maintaining a list of reserved keys?

**Comment by darrylmasson** [comment]
I realized a few things. First, insisting on "reserved config names" is trying to protect users from themselves which rarely works. Second, node configuration was done separately in two places, so this was unified.

**Review by darrylmasson — APPROVED** [review]

**Pull request merged**
